// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8QD7OLZQYCtORV_KRzugxj1MftRA3Wwc',
    appId: '1:721164138724:web:5c9c28c0c113aa11b5d4f1',
    messagingSenderId: '721164138724',
    projectId: 'chat-app-d3fb7',
    authDomain: 'chat-app-d3fb7.firebaseapp.com',
    storageBucket: 'chat-app-d3fb7.firebasestorage.app',
    measurementId: 'G-4L3S3X6NFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGmWuLBrbq9r1_sigtR-G-5dowHZaINWM',
    appId: '1:721164138724:android:5b5a90deabfda953b5d4f1',
    messagingSenderId: '721164138724',
    projectId: 'chat-app-d3fb7',
    storageBucket: 'chat-app-d3fb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC_XGWphzHkd7pL-nWOVJ7HF2AAEzG4_I',
    appId: '1:721164138724:ios:ee7d4e1cd5faff7cb5d4f1',
    messagingSenderId: '721164138724',
    projectId: 'chat-app-d3fb7',
    storageBucket: 'chat-app-d3fb7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
